apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
  KC_CACHE_STACK: kubernetes
  JAVA_OPTS_APPEND: "-Djgroups.dns.query=keycloak-headless"
  KC_DB_URL: jdbc:postgresql://35.228.136.66:5432/keycloak
  KC_DB_USERNAME: postgres