apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rater
  name: rater
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rater
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rater
    spec:
      containers:
      - image: denisratenok/rater
        name: rater
        envFrom:
          - configMapRef:
              name: rater
#          - secretRef:
#              name: rater
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /hello
            port: 8081
